### ISSUE TITLE
Text inside text box not properly visible in dark mode due to low contrast

### ISSUE THREAD

**Issue by TanayPhatak** [cerelabsteam/Llamate#16]
In dark mode, the text inside text boxes of chat window is difficult to read due to insufficient contrast between the text color and the text box background color. This issue affects the usability and accessibility of the application.

![Screenshot from 2024-07-09 14-37-40](https://github.com/cerelabsteam/Llamate/assets/89959873/6c4c3ff8-d363-4432-a6e4-b3fef1c121f2)

**Comment by parth-mangtani-cerelabs** [comment]
this seems to be a problem with inconsistent theming in the website currently. this is planned to be fixed in next few commits
